### PR TITLE
fix: use SDK volume array methods in GluonStats and VolumeChart

### LINKED ISSUE #5: Implement volume arrays
https://github.com/StabilityNexus/Gluon-Ergo-UI/blob/1c2a301ff11a8e1baa40f3effe4259bdeaf20e55/src/lib/components/blocks/dashboard/GluonStats.tsx#L104

### PR DESCRIPTION
**Pull request by sameezy667**
### Addressed Issues:
Fixes StabilityNexus/Gluon-Ergo-SDK#5

### Screenshots/Recordings:
attached network panel to see charts rendering

### Additional Notes:
Two bugs fixed in the volume chart pipeline:

1. GluonStats.tsx (line 105-106): `volumeArrays` was hardcoded as empty arrays
   `{ protonsToNeutrons: [], neutronsToProtons: [] }` — the SDK methods
   `getVolumeProtonsToNeutronsArray()` and `getVolumeNeutronsToProtonsArray()`
   were never called.

2. VolumeChart.tsx: Used a 14-iteration serial loop calling `accumulateVolume*(day)`
   for day 1–14 then diffing consecutive cumulative sums — 28 network round-trips
   to reconstruct data the SDK already stores as discrete daily buckets.
   Replaced with 2 direct `getVolume*Array()` calls and reversed the array
   for chronological chart display.

### AI Usage Disclosure:
- [x] This PR contains AI-generated code. I have read the AI Usage Policy and this PR complies with this policy. I have tested the code locally and I am responsible for it.

I have used the following AI models and tools: Claude (Anthropic), Perplexity AI

## Checklist
- [x] My PR addresses a single issue, fixes a single bug or makes a single improvement.
- [x] My code follows the project's code style and conventions
- [ ] If applicable, I have made corresponding changes or additions to the documentation
- [ ] If applicable, I have made corresponding changes or additions to tests
- [x] My changes generate no new warnings or errors
- [x] I have joined the Discord server and I will share a link to this PR with the project maintainers there
- [x] I have read the Contribution Guidelines
- [x] Once I submit my PR, CodeRabbit AI will automatically review it and I will address CodeRabbit's comments.
- [x] I have filled this PR template completely and carefully
Screenshot 2026-03-31 113817

## Changes

* **Bug Fixes**
  * Dashboard volumes now display accurate protocol volume data instead of placeholders.
* **New Features**
  * Volume chart added to the stats view and now renders from provided historical volume arrays for consistent visuals.
* **Refactor**
  * Simplified chart loading/error states and streamlined dashboard rendering for more reliable, clearer displays.

### CODE REVIEW

File: src/lib/components/blocks/dashboard/GluonStats.tsx [hunk 1]
```diff
@@ -90,8 +90,21 @@ export function GluonStats() {
           gluon.getTVL(gluonBox, oracleBox),
         ]);
 
-        // Fetch protocol metrics
-        const [volume1DayPN, volume1DayNP, volume7DayPN, volume7DayNP, volume14DayPN, volume14DayNP, circProtons, circNeutrons] = await Promise.all([
+        // Fetch protocol metrics — volume arrays come first (2 calls instead of many)
+        // getVolumeProtonsToNeutronsArray / getVolumeNeutronsToProtonsArray return a
+        // BUCKET_LEN-length array where index 0 = today, 1 = yesterday, etc.
```
Comment (DengreSarthak) [inline src/lib/components/blocks/dashboard/GluonStats.tsx]: Can you remoVe unnecessary comments.

File: src/lib/components/blocks/dashboard/GluonStats.tsx [hunk 2]
```diff
@@ -100,10 +113,12 @@ export function GluonStats() {
           gluonBox.accumulateVolumeNeutronsToProtons(14),
           gluonBox.getProtonsCirculatingSupply(),
           gluonBox.getNeutronsCirculatingSupply(),
+          // SDK Issue #5 fix: use the direct array methods instead of empty placeholders
+          gluonBox.getVolumeProtonsToNeutronsArray(),
+          gluonBox.getVolumeNeutronsToProtonsArray(),
```
Comment (DengreSarthak) [inline src/lib/components/blocks/dashboard/GluonStats.tsx:117]: See code rabbit comment here.

File: bun.lock
Comment (DengreSarthak) [inline bun.lock:1]: RemoVe this file.
